### ISSUE TITLE
token_deposit not working

### ISSUE THREAD

**Issue by kongliangzhong** [OffchainLabs/arbitrum-tutorials#16]
`yarn run token_deposit` failed with the following error:

```
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.4.2)
    at Logger.makeError (/home/ubuntu/research/arbitrum/arbitrum-tutorials/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
    at Logger.throwError (/home/ubuntu/research/arbitrum/arbitrum-tutorials/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
    at JsonRpcProvider.<anonymous> (/home/ubuntu/research/arbitrum/arbitrum-tutorials/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:396:23)
    at step (/home/ubuntu/research/arbitrum/arbitrum-tutorials/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/ubuntu/research/arbitrum/arbitrum-tutorials/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/ubuntu/research/arbitrum/arbitrum-tutorials/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```

And the environmental variables were properly set.

**Comment by singularTnT** [comment]
Just remove quotes in .env file.

**Comment by kongliangzhong** [comment]
> Just remove quotes in .env file.

It works, thanks!
