### ISSUE TITLE
Custom token bridging example fails on could not detect network

### ISSUE THREAD

**Issue by jeffywu** [OffchainLabs/arbitrum-tutorials#41]
When running `npm run custom-token-bridging` from the custom-token-bridging folder I get the following error:

My .env variables are set, this appears to be an issue with the L2 provider:
Set as: 
```
# Hosted Aggregator Node (JSON-RPC Endpoint)
L2RPC="https://rinkeby.arbitrum.io/rpc" 
```

Added this code and it appears to fail at the `l2Wallet.getChainId()` call:
```
  await arbLog('Setting Up Your Token With The Generic Custom Gateway')
  /**
  * Use wallets to create an arb-ts bridge instance
  * We'll use bridge for its convenience methods around registering tokens to the custom gateway
  */
 console.log("chainId L1", await l1Wallet.getChainId())
 console.log("chainId L2", await l2Wallet.getChainId())
 console.log("completed")
```

Output:
```
chainId L1 4
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.4.5)
    at Logger.makeError (/home/jwu/code/notional-finance/arbitrum-tutorials/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/home/jwu/code/notional-finance/arbitrum-tutorials/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at JsonRpcProvider.<anonymous> (/home/jwu/code/notional-finance/arbitrum-tutorials/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:396:23)
    at step (/home/jwu/code/notional-finance/arbitrum-tutorials/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/jwu/code/notional-finance/arbitrum-tutorials/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/jwu/code/notional-finance/arbitrum-tutorials/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at runNextTicks (internal/process/task_queues.js:60:5)
    at listOnTimeout (internal/timers.js:524:9)
    at processTimers (internal/timers.js:498:7) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```

**Comment by maxweng** [comment]
I got the same issue and resolved it by using the InfuraProvider, instead of JsonRpcProvider in the examples, like this:

```
const l2Provider = new providers.InfuraProvider(
  'arbitrum-rinkeby',
  process.env.INFURA_KEY
)

```
you may also need to upgrade your ethers.js to v5.5.2 or later.

**Comment by ssolson** [comment]
I am having this same issue. The solution above and no other attempt I have made has solved it has worked.

**Comment by ssolson** [comment]
So the isue seems to be around how the L2RPC is read in. By removing the quatoe around L2RPC fixed the issue.

SO console. log showed 
```
l2Wallet:  Wallet {
  _isSigner: true,
  _signingKey: [Function (anonymous)],
  _mnemonic: [Function (anonymous)],
  address: '0x1B3ad5fA50Ae32875748107F4b2160829CC10536',
  provider: JsonRpcProvider {
    _isProvider: true,
    _events: [],
    _emitted: { block: -2 },
    formatter: Formatter { formats: [Object] },
    anyNetwork: false,
    _networkPromise: Promise { <rejected> [Error] },
    _maxInternalBlockNumber: -1024,
    _lastBlockNumber: -2,
    _pollingInterval: 4000,
    _fastQueryDate: 0,
    connection: { url: '"https://rinkeby.arbitrum.io/rpc"' },
    _nextId: 44,
    _eventLoopCache: { detectNetwork: null, eth_chainId: null }
  }
}
```

So I set the L2RPC as 

```
L2RPC=https://rinkeby.arbitrum.io/rpc 
```
