### ISSUE TITLE
Error: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.5.0)

### ISSUE THREAD

**Issue by purevolcano106** [OffchainLabs/arbitrum-tutorials#45]
When I run this commant 'yarn run token-deposit', the result is as follows.

yarn run v1.22.17
$ hardhat run scripts/exec.js
Environmental variables properly set 👍
                            🔵🔵
                           🔵  🔵
                          🔵    🔵
                         🔵      🔵
                        🔵        🔵
                       🔵          🔵
                      🔵            🔵
                     🔵              🔵
                    🔵                🔵
                   🔵                  🔵
                  🔵                    🔵
                 🔵                      🔵
                🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵
               🔵                          🔵
              🔵                            🔵
             🔵                              🔵
            🔵                                🔵
           🔵                                  🔵
          🔵                                    🔵
         🔵                                      🔵
        🔵                                        🔵        
       🔵                                          🔵       
      🔵                                            🔵      
     🔵                                              🔵     
    🔵                                                🔵    
Arbitrum Demo: Deposit token using arb-ts
Lets
Go ➡️
...🚀

Deploying the test DappToken to L1
DappToken is deployed to L1 at 0xa4C7B1FEC327EA8cfC48Ad0D748feA6d662EF83f
0xa4C7B1FEC327EA8cfC48Ad0D748feA6d662EF83f
You successfully allowed the Arbitrum Bridge to spend DappToken 0x04f724d93d94d231877770553445f15625d79f48a1d7926b9ebf38e2d816d579
Error: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.5.0)
    at Logger.makeError (E:\Git\arbitrum-tutorials\packages\token-deposit\node_modules\@ethersproject\logger\src.ts\index.ts:225:28)
    at Logger.throwError (E:\Git\arbitrum-tutorials\packages\token-deposit\node_modules\@ethersproject\logger\src.ts\index.ts:237:20)
    at Logger.throwArgumentError (E:\Git\arbitrum-tutorials\packages\token-deposit\node_modules\@ethersproject\logger\src.ts\index.ts:241:21)
    at E:\Git\arbitrum-tutorials\packages\token-deposit\node_modules\@ethersproject\contracts\src.ts\index.ts:120:16
    at step (E:\Git\arbitrum-tutorials\packages\token-deposit\node_modules\@ethersproject\contracts\lib\index.js:48:23)
    at Object.next (E:\Git\arbitrum-tutorials\packages\token-deposit\node_modules\@ethersproject\contracts\lib\index.js:29:53)
    at fulfilled (E:\Git\arbitrum-tutorials\packages\token-deposit\node_modules\@ethersproject\contracts\lib\index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'invalid address or ENS name',
  code: 'INVALID_ARGUMENT',
  argument: 'name',
  value: undefined
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Why does this problem occur?

**Comment by maxweng** [comment]
Apparently, some of the examples are outdated. you just need to update the deposit call to something like this: 
```
const depositTx = await bridge.deposit({
  erc20L1Address: erc20Address,
  amount: tokenDepositAmount,
})
```
