### ISSUE TITLE
outbox-execute fails to withdraw, prompts: No NodeCreated events found

### ISSUE THREAD

**Issue by songjianyang** [OffchainLabs/arbitrum-tutorials#80]
First, make a normal withdrawal:

```
yarn run withdrawETH
yarn run v1.22.19
$ hardhat run scripts/exec.js
Environmental variables properly set 👍
                            🔵🔵
                           🔵  🔵
                          🔵    🔵
                         🔵      🔵
                        🔵        🔵
                       🔵          🔵
                      🔵            🔵
                     🔵              🔵
                    🔵                🔵
                   🔵                  🔵
                  🔵                    🔵
                 🔵                      🔵
                🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵
               🔵                          🔵
              🔵                            🔵
             🔵                              🔵
            🔵                                🔵
           🔵                                  🔵
          🔵                                    🔵
         🔵                                      🔵
        🔵                                        🔵
       🔵                                          🔵
      🔵                                            🔵
     🔵                                              🔵
    🔵                                                🔵
Arbitrum Demo: Withdraw Eth via Arbitrum SDK
Lets
Go ➡️
...🚀

Wallet properly funded: initiating withdrawal now
Ether withdrawal initiated! 🥳 0xf8a6f02c5473e786844143502da7bb8a01bae40dd5dbfbbe086de05ef3cd3267
Withdrawal data: [
  [
    '0x683642c22feDE752415D4793832Ab75EFdF6223c',
    '0x683642c22feDE752415D4793832Ab75EFdF6223c',
    BigNumber {
      _hex: '0xa2817bea8b6cac5396ae6d63456d574cbc6665c1dc87794530c8224d6aa846a7',
      _isBigNumber: true
    },
    BigNumber { _hex: '0x01', _isBigNumber: true },
    BigNumber { _hex: '0x1b', _isBigNumber: true },
    BigNumber { _hex: '0x0594', _isBigNumber: true },
    BigNumber { _hex: '0x6360d98c', _isBigNumber: true },
    BigNumber { _hex: '0xe8d4a51000', _isBigNumber: true },
    '0x',
    caller: '0x683642c22feDE752415D4793832Ab75EFdF6223c',
    destination: '0x683642c22feDE752415D4793832Ab75EFdF6223c',
    hash: BigNumber {
      _hex: '0xa2817bea8b6cac5396ae6d63456d574cbc6665c1dc87794530c8224d6aa846a7',
      _isBigNumber: true
    },
    position: BigNumber { _hex: '0x01', _isBigNumber: true },
    arbBlockNum: BigNumber { _hex: '0x1b', _isBigNumber: true },
    ethBlockNum: BigNumber { _hex: '0x0594', _isBigNumber: true },
    timestamp: BigNumber { _hex: '0x6360d98c', _isBigNumber: true },
    callvalue: BigNumber { _hex: '0xe8d4a51000', _isBigNumber: true },
    data: '0x'
  ]
]
To to claim funds (after dispute period), see outbox-execute repo 🫡
Done in 7.23s.

```

An error was encountered when calling outbox-exec
```
yarn outbox-exec --txhash 0xf8a6f02c5473e78684414350
2da7bb8a01bae40dd5dbfbbe086de05ef3cd3267
yarn run v1.22.19
$ hardhat outbox-exec --txhash 0xf8a6f02c5473e786844143502da7bb8a01bae40dd5dbfbbe086de05ef3cd3267
Environmental variables properly set 👍
                            🔵🔵
                           🔵  🔵
                          🔵    🔵
                         🔵      🔵
                        🔵        🔵
                       🔵          🔵
                      🔵            🔵
                     🔵              🔵
                    🔵                🔵
                   🔵                  🔵
                  🔵                    🔵
                 🔵                      🔵
                🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵
               🔵                          🔵
              🔵                            🔵
             🔵                              🔵
            🔵                                🔵
           🔵                                  🔵
          🔵                                    🔵
         🔵                                      🔵
        🔵                                        🔵
       🔵                                          🔵
      🔵                                            🔵
     🔵                                              🔵
    🔵                                                🔵
Arbitrum Demo: Outbox Execution
Lets
Go ➡️


...🚀

An unexpected error occurred:

ArbSdkError: No NodeCreated events found
    at L2ToL1MessageReaderNitro.getBlockFromNodeNum (/home/test/arbitrum-tutorials2/node_modules/@arbitrum/sdk/dist/lib/message/L2ToL1MessageNitro.js:122:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at L2ToL1MessageReaderNitro.getSendProps (/home/test/arbitrum-tutorials2/node_modules/@arbitrum/sdk/dist/lib/message/L2ToL1MessageNitro.js:144:38)
    at L2ToL1MessageReaderNitro.status (/home/test/arbitrum-tutorials2/node_modules/@arbitrum/sdk/dist/lib/message/L2ToL1MessageNitro.js:85:39)
    at L2ToL1MessageWriter.status (/home/test/arbitrum-tutorials2/node_modules/@arbitrum/sdk/dist/lib/message/L2ToL1Message.js:160:20)
    at module.exports (/home/test/arbitrum-tutorials2/packages/outbox-execute/scripts/exec.js:95:8)
    at SimpleTaskDefinition.action (/home/test/arbitrum-tutorials2/packages/outbox-execute/hardhat.config.js:19:5)
    at Environment._runTaskDefinition (/home/test/arbitrum-tutorials2/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/home/test/arbitrum-tutorials2/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at main (/home/test/arbitrum-tutorials2/node_modules/hardhat/src/internal/cli/cli.ts:256:5) {
  inner: undefined
}
error Command failed with exit code 1.
```

**Comment by songjianyang** [comment]
@gzeoneth

**Comment by mahsamoosavi** [comment]
@songjianyang Which network are you using? Can you give me a block explorer link to your withdrawal tx 0xf8a6f02c5473e786844143502da7bb8a01bae40dd5dbfbbe086de05ef3cd3267?

**Comment by songjianyang** [comment]
> @songjianyang Which network are you using? Can you give me a block explorer link to your withdrawal tx `0xf8a6f02c5473e786844143502da7bb8a01bae40dd5dbfbbe086de05ef3cd3267`?
> 
> I can't find any such withdraw on any of our networks initiated from your address 🤨`0x683642c22feDE752415D4793832Ab75EFdF6223c`

I use local chain. This problem has now been resolved, and the local chain will no longer report errors after running for a period of time. Thank you
