### ISSUE TITLE
How to run on local dev network?

### ISSUE THREAD

**Issue by s7v7nislands** [OffchainLabs/arbitrum-tutorials#86]
after using `test-node.bash` in nitro repo,  create a local test env

`
ArbSdkError: Unrecognized network 412346.
    at getNetwork (/Users/user/source/git/arbitrum-tutorials/node_modules/@arbitrum/sdk/dist/lib/dataEntities/networks.js:236:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at main (/Users/user/source/git/arbitrum-tutorials/packages/eth-deposit/scripts/exec.js:36:21) {
  inner: undefined
}
`

it seems the arbitrum-sdk only support hardcode network?

**Comment by s7v7nislands** [comment]
I find the solution: addCustomNetwork. use the localNetwork.json from after run `test-node.bash`. should we add this tip to the readme?

**Comment by DZGoldman** [comment]
> should we add this tip to the readme?
Yes, that's be great! ty

**Comment by TucksonDev** [comment]
The current `customNetwork.json` file includes already the information of the testnode, and the [README](https://github.com/OffchainLabs/arbitrum-tutorials#how-to-run-the-tutorials-against-a-custom-network) contains instructions to update that file for any other network.
